config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
      get 'like', to: 'likes#new', as: 'new_like'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_default_values

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  after_create :increment_posts_counter
  after_save :update_counter
  after_destroy :decrement_posts

  def update_counter
    user.update(posts_counter: user.posts.count)
  end

  def increment_posts_counter
    user.increment!(:posts_counter)
    user.save
    user.reload
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def set_default_values
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  def decrement_posts
    user.decrement!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    begin
      @user = User.find(params[:user_id])
      @posts = @user.posts.order(created_at: :asc)
      render json: @posts
    rescue ActiveRecord::RecordNotFound
      render json: 'Posts not found'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(post: @post)
    render :show
  end

  def new
    @user = User.find(current_user.id)
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @user = User.find(current_user.id)

    @post.author_id = @user.id
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      flash[:notice] = 'Post created successfully.'
      redirect_to user_path(@post.author_id), notice: 'Post created successfully'
    else
      render :new, alert: 'Error creating post'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = 'Post deleted successfully!'
      redirect_to user_posts_path(current_user)
    else
      flash[:alert] = @post.errors.full_messages.first if @post.errors.any?
      render :show, status: 400
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.htm.erb
<% unless comments.empty? %>
  <div class='comment'>
    <% comments.each do |comment| %>
      <div class='comments'>
        Username: <%= comment.author.name %>
        Comment: <%= comment.text %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_comment.html.erb
<% unless comments.empty? %>
  <div class='comment'>
    <% comments.each do |comment| %>
      <div class='comments'>
        Username: <%= comment.author.name %>
        Comment: <%= comment.text %>
        <% if can? :destroy, comment %>
          <button type="button" class="btn delete-btn">
            <%= link_to "Delete Comment", user_post_comment_path(author_id: comment.author_id, post_id: comment.post.id, id: comment.id), data: { turbo_method: :delete } %>
          </button>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<br />

app/views/posts/index.html.erb
<%= render partial: '/users/userheader', locals: { user: @user } %>
<div class='container'><br />
<%= link_to "Create a new post", new_user_post_path(@current_user) %> <br />
<% @posts.each_with_index do |post, index| %>
  <% link = "posts/#{post.id}" %>
  <a href=<%= link %>>
    <div class='user-posts'>
      <h4>Post #<%= index + 1 %></h4>
      <p><%= post.text %></p>
      <div class='stats'>
        <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
      </div>
        <% if can? :destroy, post %>
          <button type="button" class="btn delete-btn">
            <%= link_to "Delete Post", user_post_path(user_id: post.author_id, id: post.id), data: { turbo_method: :delete } %>
          </button>
        <% end %>
    </div>
  </a>
  <%= render partial: 'comment', locals: {comments: post.recent_comments} %>
<% end %>
</div>
<br />
<% linkPagina = "#{@user.id}/posts" %>
<a href=<%= linkPagina %> >
  <button class='pagination'>pagination</button>
</a>

app/views/posts/new.html.erb
<%= form_with(model: [current_user, @post], local: true) do |f| %>
  <div class="field">
    <%= f.label :title %> <br />
    <%= f.text_field :title, class: 'form-group' %>
  </div>
  <div class="field">
    <%= f.label :text %> <br />
    <%= f.text_area :text, class: 'form-group'  %>
  </div>
  <div class="field">
    <%= f.submit 'Submit', class: 'form-group-btn'  %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Specific post</h1>
<div class='single-post'>
  <h4>Post #<%= @post.id %> by <%= @post.user.name %></h4>
  <span>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></span>
  <p>
    <%= @post.text %>
  </p>
</div>
<%= render partial: 'comment', locals: { comments: @post.comments } %>
<%= link_to 'Add a comment', new_user_post_comment_path(@current_user, post_id: @post.id, user_id: 1) %> 
<%= button_to "Like", user_post_likes_path(@current_user, post_id: @post.id, user_id: 1), method: :post, class: 'form-group-btn field' %>